version: '3.8'
services:
  npm:
    build: 
      context: ./
      dockerfile: Dockerfile
    # stdin_open & tty is for -it(interactive mode)
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

